/**
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';


const Configuration = {
    // The base Uri for API calls
    BASEURI: 'https://api.pagar.me/core/v5',

    // The username to use with basic authentication
    // TODO: Replace the BasicAuthUserName with an appropriate value
    // basicAuthUserName: 'rudson@precode.com.br',
    basicAuthUserName: '',

    // The password to use with basic authentication
    // TODO: Replace the BasicAuthPassword with an appropriate value
    basicAuthPassword: '',

};

module.exports = Configuration;
