/**
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ListInvoicesResponse = require('../lib/Models/ListInvoicesResponse');
const GetCheckoutBoletoPaymentResponse = require('../lib/Models/GetCheckoutBoletoPaymentResponse');
const UpdatePriceBracketRequest = require('../lib/Models/UpdatePriceBracketRequest');
const UpdateSubscriptionBillingDateRequest =
  require('../lib/Models/UpdateSubscriptionBillingDateRequest');
const ListChargesResponse = require('../lib/Models/ListChargesResponse');
const ListSubscriptionsResponse = require('../lib/Models/ListSubscriptionsResponse');
const PagingResponse = require('../lib/Models/PagingResponse');
const CreateCardOptionsRequest = require('../lib/Models/CreateCardOptionsRequest');
const ListTransactionsResponse = require('../lib/Models/ListTransactionsResponse');
const GetPlanItemResponse = require('../lib/Models/GetPlanItemResponse');
const ListCardsResponse = require('../lib/Models/ListCardsResponse');
const GetPhonesResponse = require('../lib/Models/GetPhonesResponse');
const CreateCardTokenRequest = require('../lib/Models/CreateCardTokenRequest');
const GetPricingSchemeResponse = require('../lib/Models/GetPricingSchemeResponse');
const GetPriceBracketResponse = require('../lib/Models/GetPriceBracketResponse');
const GetTokenResponse = require('../lib/Models/GetTokenResponse');
const ListCustomersResponse = require('../lib/Models/ListCustomersResponse');
const UpdatePlanItemRequest = require('../lib/Models/UpdatePlanItemRequest');
const UpdateSubscriptionItemRequest = require('../lib/Models/UpdateSubscriptionItemRequest');
const GetChargeResponse = require('../lib/Models/GetChargeResponse');
const GetBankTransferTransactionResponse =
  require('../lib/Models/GetBankTransferTransactionResponse');
const GetCheckoutPaymentSettingsResponse =
  require('../lib/Models/GetCheckoutPaymentSettingsResponse');
const ListPlansResponse = require('../lib/Models/ListPlansResponse');
const GetOrderResponse = require('../lib/Models/GetOrderResponse');
const GetAntifraudResponse = require('../lib/Models/GetAntifraudResponse');
const CreateSetupRequest = require('../lib/Models/CreateSetupRequest');
const UpdateChargeCardRequest = require('../lib/Models/UpdateChargeCardRequest');
const CreatePhoneRequest = require('../lib/Models/CreatePhoneRequest');
const CreateCheckoutDebitCardPaymentRequest =
  require('../lib/Models/CreateCheckoutDebitCardPaymentRequest');
const CreatePlanItemRequest = require('../lib/Models/CreatePlanItemRequest');
const CreateCaptureChargeRequest = require('../lib/Models/CreateCaptureChargeRequest');
const GetSafetyPayTransactionResponse = require('../lib/Models/GetSafetyPayTransactionResponse');
const CreateTokenRequest = require('../lib/Models/CreateTokenRequest');
const UpdateMetadataRequest = require('../lib/Models/UpdateMetadataRequest');
const CreateCheckoutCardInstallmentOptionRequest =
  require('../lib/Models/CreateCheckoutCardInstallmentOptionRequest');
const UpdatePricingSchemeRequest = require('../lib/Models/UpdatePricingSchemeRequest');
const ListAccessTokensResponse = require('../lib/Models/ListAccessTokensResponse');
const ListUsagesResponse = require('../lib/Models/ListUsagesResponse');
const UpdateSubscriptionCardRequest = require('../lib/Models/UpdateSubscriptionCardRequest');
const GetSetupResponse = require('../lib/Models/GetSetupResponse');
const GetPlanResponse = require('../lib/Models/GetPlanResponse');
const UpdatePlanRequest = require('../lib/Models/UpdatePlanRequest');
const CreatePriceBracketRequest = require('../lib/Models/CreatePriceBracketRequest');
const GetCardTokenResponse = require('../lib/Models/GetCardTokenResponse');
const GetCheckoutCardInstallmentOptionsResponse =
  require('../lib/Models/GetCheckoutCardInstallmentOptionsResponse');
const CreateCancelSubscriptionRequest = require('../lib/Models/CreateCancelSubscriptionRequest');
const UpdateCardRequest = require('../lib/Models/UpdateCardRequest');
const CreatePlanRequest = require('../lib/Models/CreatePlanRequest');
const CreateBankTransferPaymentRequest = require('../lib/Models/CreateBankTransferPaymentRequest');
const CreatePricingSchemeRequest = require('../lib/Models/CreatePricingSchemeRequest');
const CreatePhonesRequest = require('../lib/Models/CreatePhonesRequest');
const CreateVoucherPaymentRequest = require('../lib/Models/CreateVoucherPaymentRequest');
const CreateCheckoutBoletoPaymentRequest =
  require('../lib/Models/CreateCheckoutBoletoPaymentRequest');
const UpdateChargeDueDateRequest = require('../lib/Models/UpdateChargeDueDateRequest');
const CreateAccessTokenRequest = require('../lib/Models/CreateAccessTokenRequest');
const GetPhoneResponse = require('../lib/Models/GetPhoneResponse');
const GetVoucherTransactionResponse = require('../lib/Models/GetVoucherTransactionResponse');
const ListSubscriptionItemsResponse = require('../lib/Models/ListSubscriptionItemsResponse');
const ListOrderResponse = require('../lib/Models/ListOrderResponse');
const ListAddressesResponse = require('../lib/Models/ListAddressesResponse');
const GetDiscountResponse = require('../lib/Models/GetDiscountResponse');
const GetCustomerResponse = require('../lib/Models/GetCustomerResponse');
const CreateAddressRequest = require('../lib/Models/CreateAddressRequest');
const CreateSubscriptionItemRequest = require('../lib/Models/CreateSubscriptionItemRequest');
const CreateOrderRequest = require('../lib/Models/CreateOrderRequest');
const GetGatewayResponseResponse = require('../lib/Models/GetGatewayResponseResponse');
const CreateDeviceRequest = require('../lib/Models/CreateDeviceRequest');
const UpdateSubscriptionAffiliationIdRequest =
  require('../lib/Models/UpdateSubscriptionAffiliationIdRequest');
const GetIncrementResponse = require('../lib/Models/GetIncrementResponse');
const CreateThreeDSecureRequest = require('../lib/Models/CreateThreeDSecureRequest');
const UpdateChargePaymentMethodRequest = require('../lib/Models/UpdateChargePaymentMethodRequest');
const GetRecipientResponse = require('../lib/Models/GetRecipientResponse');
const UpdateRecipientRequest = require('../lib/Models/UpdateRecipientRequest');
const GetGatewayRecipientResponse = require('../lib/Models/GetGatewayRecipientResponse');
const ListIncrementsResponse = require('../lib/Models/ListIncrementsResponse');
const CreateAnticipationRequest = require('../lib/Models/CreateAnticipationRequest');
const GetAnticipationLimitsResponse = require('../lib/Models/GetAnticipationLimitsResponse');
const GetInvoiceItemResponse = require('../lib/Models/GetInvoiceItemResponse');
const CreateDiscountRequest = require('../lib/Models/CreateDiscountRequest');
const GetCardResponse = require('../lib/Models/GetCardResponse');
const CreateBankAccountRequest = require('../lib/Models/CreateBankAccountRequest');
const GetBalanceResponse = require('../lib/Models/GetBalanceResponse');
const UpdateOrderItemRequest = require('../lib/Models/UpdateOrderItemRequest');
const CreateBoletoPaymentRequest = require('../lib/Models/CreateBoletoPaymentRequest');
const ListAnticipationResponse = require('../lib/Models/ListAnticipationResponse');
const UpdateAddressRequest = require('../lib/Models/UpdateAddressRequest');
const GetBoletoTransactionResponse = require('../lib/Models/GetBoletoTransactionResponse');
const GetLocationResponse = require('../lib/Models/GetLocationResponse');
const GetSubscriptionItemResponse = require('../lib/Models/GetSubscriptionItemResponse');
const GetDebitCardTransactionResponse = require('../lib/Models/GetDebitCardTransactionResponse');
const CreateTransferSettingsRequest = require('../lib/Models/CreateTransferSettingsRequest');
const CreateTransferRequest = require('../lib/Models/CreateTransferRequest');
const GetGatewayErrorResponse = require('../lib/Models/GetGatewayErrorResponse');
const ListTransferResponse = require('../lib/Models/ListTransferResponse');
const CreateUsageRequest = require('../lib/Models/CreateUsageRequest');
const CreatePaymentAuthenticationRequest =
  require('../lib/Models/CreatePaymentAuthenticationRequest');
const UpdateInvoiceStatusRequest = require('../lib/Models/UpdateInvoiceStatusRequest');
const GetUsageResponse = require('../lib/Models/GetUsageResponse');
const CreateSubscriptionRequest = require('../lib/Models/CreateSubscriptionRequest');
const CreateApplePayRequest = require('../lib/Models/CreateApplePayRequest');
const GetAnticipationLimitResponse = require('../lib/Models/GetAnticipationLimitResponse');
const UpdateCustomerRequest = require('../lib/Models/UpdateCustomerRequest');
const GetSubscriptionResponse = require('../lib/Models/GetSubscriptionResponse');
const GetPeriodResponse = require('../lib/Models/GetPeriodResponse');
const CreateDebitCardPaymentRequest = require('../lib/Models/CreateDebitCardPaymentRequest');
const CreateApplePayHeaderRequest = require('../lib/Models/CreateApplePayHeaderRequest');
const CreateLocationRequest = require('../lib/Models/CreateLocationRequest');
const UpdateOrderStatusRequest = require('../lib/Models/UpdateOrderStatusRequest');
const CreateCreditCardPaymentRequest = require('../lib/Models/CreateCreditCardPaymentRequest');
const ListDiscountsResponse = require('../lib/Models/ListDiscountsResponse');
const CreateRecipientRequest = require('../lib/Models/CreateRecipientRequest');
const GetTransferResponse = require('../lib/Models/GetTransferResponse');
const ListRecipientResponse = require('../lib/Models/ListRecipientResponse');
const GetDeviceResponse = require('../lib/Models/GetDeviceResponse');
const CreatePaymentRequest = require('../lib/Models/CreatePaymentRequest');
const GetTransactionResponse = require('../lib/Models/GetTransactionResponse');
const UpdateRecipientBankAccountRequest =
  require('../lib/Models/UpdateRecipientBankAccountRequest');
const UpdateTransferSettingsRequest = require('../lib/Models/UpdateTransferSettingsRequest');
const GetBillingAddressResponse = require('../lib/Models/GetBillingAddressResponse');
const CreateIncrementRequest = require('../lib/Models/CreateIncrementRequest');
const CreateCashPaymentRequest = require('../lib/Models/CreateCashPaymentRequest');
const CreateCancelChargeRequest = require('../lib/Models/CreateCancelChargeRequest');
const CreateShippingRequest = require('../lib/Models/CreateShippingRequest');
const GetCheckoutCreditCardPaymentResponse =
  require('../lib/Models/GetCheckoutCreditCardPaymentResponse');
const CreateChargeRequest = require('../lib/Models/CreateChargeRequest');
const CreateTransfer = require('../lib/Models/CreateTransfer');
const CreateTransactionReportFileRequest =
  require('../lib/Models/CreateTransactionReportFileRequest');
const CreateCardRequest = require('../lib/Models/CreateCardRequest');
const CreateEmvDataDukptDecryptRequest = require('../lib/Models/CreateEmvDataDukptDecryptRequest');
const GetWithdrawTargetResponse = require('../lib/Models/GetWithdrawTargetResponse');
const CreateCancelChargeSplitRulesRequest =
  require('../lib/Models/CreateCancelChargeSplitRulesRequest');
const UpdateSubscriptionStartAtRequest = require('../lib/Models/UpdateSubscriptionStartAtRequest');
const CreatePixPaymentRequest = require('../lib/Models/CreatePixPaymentRequest');
const GetChargesSummaryResponse = require('../lib/Models/GetChargesSummaryResponse');
const CreatePrivateLabelPaymentRequest = require('../lib/Models/CreatePrivateLabelPaymentRequest');
const UpdateAutomaticAnticipationSettingsRequest =
  require('../lib/Models/UpdateAutomaticAnticipationSettingsRequest');
const GetSplitResponse = require('../lib/Models/GetSplitResponse');
const ListTransactionsFilesResponse = require('../lib/Models/ListTransactionsFilesResponse');
const CreateEmvDataTlvDecryptRequest = require('../lib/Models/CreateEmvDataTlvDecryptRequest');
const CreateEmvDecryptRequest = require('../lib/Models/CreateEmvDecryptRequest');
const GetWithdrawSourceResponse = require('../lib/Models/GetWithdrawSourceResponse');
const CreateConfirmPaymentRequest = require('../lib/Models/CreateConfirmPaymentRequest');
const GetCheckoutDebitCardPaymentResponse =
  require('../lib/Models/GetCheckoutDebitCardPaymentResponse');
const GetAnticipationResponse = require('../lib/Models/GetAnticipationResponse');
const GetPrivateLabelTransactionResponse =
  require('../lib/Models/GetPrivateLabelTransactionResponse');
const CreateAutomaticAnticipationSettingsRequest =
  require('../lib/Models/CreateAutomaticAnticipationSettingsRequest');
const GetCashTransactionResponse = require('../lib/Models/GetCashTransactionResponse');
const UpdateSubscriptionMinimumPriceRequest =
  require('../lib/Models/UpdateSubscriptionMinimumPriceRequest');
const CreateGooglePayRequest = require('../lib/Models/CreateGooglePayRequest');
const UpdateSubscriptionPaymentMethodRequest =
  require('../lib/Models/UpdateSubscriptionPaymentMethodRequest');
const CreateAntifraudRequest = require('../lib/Models/CreateAntifraudRequest');
const GetCheckoutBankTransferPaymentResponse =
  require('../lib/Models/GetCheckoutBankTransferPaymentResponse');
const GetBankAccountResponse = require('../lib/Models/GetBankAccountResponse');
const CreateOrderItemRequest = require('../lib/Models/CreateOrderItemRequest');
const CreateSplitOptionsRequest = require('../lib/Models/CreateSplitOptionsRequest');
const GetTransactionReportFileResponse = require('../lib/Models/GetTransactionReportFileResponse');
const CreateClearSaleRequest = require('../lib/Models/CreateClearSaleRequest');
const GetUsageReportResponse = require('../lib/Models/GetUsageReportResponse');
const ListTransfers = require('../lib/Models/ListTransfers');
const PixAdditionalInformation = require('../lib/Models/PixAdditionalInformation');
const GetShippingResponse = require('../lib/Models/GetShippingResponse');
const UpdateCurrentCycleEndDateRequest = require('../lib/Models/UpdateCurrentCycleEndDateRequest');
const CreateCheckoutBankTransferRequest =
  require('../lib/Models/CreateCheckoutBankTransferRequest');
const CreateCardPaymentContactlessRequest =
  require('../lib/Models/CreateCardPaymentContactlessRequest');
const CreateCustomerRequest = require('../lib/Models/CreateCustomerRequest');
const GetTransferTargetResponse = require('../lib/Models/GetTransferTargetResponse');
const ListWithdrawals = require('../lib/Models/ListWithdrawals');
const GetCheckoutPaymentResponse = require('../lib/Models/GetCheckoutPaymentResponse');
const CreateEmvDataDecryptRequest = require('../lib/Models/CreateEmvDataDecryptRequest');
const GetWithdrawResponse = require('../lib/Models/GetWithdrawResponse');
const GetAutomaticAnticipationResponse = require('../lib/Models/GetAutomaticAnticipationResponse');
const CreateCheckoutPaymentRequest = require('../lib/Models/CreateCheckoutPaymentRequest');
const CreateCheckoutCreditCardPaymentRequest =
  require('../lib/Models/CreateCheckoutCreditCardPaymentRequest');
const GetTransfer = require('../lib/Models/GetTransfer');
const CreateSplitRequest = require('../lib/Models/CreateSplitRequest');
const UpdateCurrentCycleStatusRequest = require('../lib/Models/UpdateCurrentCycleStatusRequest');
const CreateInvoiceRequest = require('../lib/Models/CreateInvoiceRequest');
const GetTransferSettingsResponse = require('../lib/Models/GetTransferSettingsResponse');
const CreatePeriodRequest = require('../lib/Models/CreatePeriodRequest');
const GetPaymentAuthenticationResponse = require('../lib/Models/GetPaymentAuthenticationResponse');
const GetThreeDSecureResponse = require('../lib/Models/GetThreeDSecureResponse');
const CreateGooglePayHeaderRequest = require('../lib/Models/CreateGooglePayHeaderRequest');
const GetOrderItemResponse = require('../lib/Models/GetOrderItemResponse');
const GetAddressResponse = require('../lib/Models/GetAddressResponse');
const CreateCardPaymentContactlessPOIRequest =
  require('../lib/Models/CreateCardPaymentContactlessPOIRequest');
const CreateWithdrawRequest = require('../lib/Models/CreateWithdrawRequest');
const GetSplitOptionsResponse = require('../lib/Models/GetSplitOptionsResponse');
const GetCreditCardTransactionResponse = require('../lib/Models/GetCreditCardTransactionResponse');
const ListChargeTransactionsResponse = require('../lib/Models/ListChargeTransactionsResponse');
const ListCyclesResponse = require('../lib/Models/ListCyclesResponse');
const GetInvoiceResponse = require('../lib/Models/GetInvoiceResponse');
const GetAccessTokenResponse = require('../lib/Models/GetAccessTokenResponse');
const GetTransferSourceResponse = require('../lib/Models/GetTransferSourceResponse');
const CreateSubMerchantRequest = require('../lib/Models/CreateSubMerchantRequest');
const GetPixTransactionResponse = require('../lib/Models/GetPixTransactionResponse');
const UpdateSubscriptionDueDaysRequest = require('../lib/Models/UpdateSubscriptionDueDaysRequest');
const CreateCheckoutPixPaymentRequest = require('../lib/Models/CreateCheckoutPixPaymentRequest');
const GetCheckoutPixPaymentResponse = require('../lib/Models/GetCheckoutPixPaymentResponse');
const CreateSubscriptionSplitRequest = require('../lib/Models/CreateSubscriptionSplitRequest');
const UpdateSubscriptionSplitRequest = require('../lib/Models/UpdateSubscriptionSplitRequest');
const GetSubscriptionSplitResponse = require('../lib/Models/GetSubscriptionSplitResponse');
const GetPixPayerResponse = require('../lib/Models/GetPixPayerResponse');
const GetPixBankAccountResponse = require('../lib/Models/GetPixBankAccountResponse');
const ErrorException = require('../lib/Exceptions/ErrorException');

const classMap = {
    ListInvoicesResponse,
    GetCheckoutBoletoPaymentResponse,
    UpdatePriceBracketRequest,
    UpdateSubscriptionBillingDateRequest,
    ListChargesResponse,
    ListSubscriptionsResponse,
    PagingResponse,
    CreateCardOptionsRequest,
    ListTransactionsResponse,
    GetPlanItemResponse,
    ListCardsResponse,
    GetPhonesResponse,
    CreateCardTokenRequest,
    GetPricingSchemeResponse,
    GetPriceBracketResponse,
    GetTokenResponse,
    ListCustomersResponse,
    UpdatePlanItemRequest,
    UpdateSubscriptionItemRequest,
    GetChargeResponse,
    GetBankTransferTransactionResponse,
    GetCheckoutPaymentSettingsResponse,
    ListPlansResponse,
    GetOrderResponse,
    GetAntifraudResponse,
    CreateSetupRequest,
    UpdateChargeCardRequest,
    CreatePhoneRequest,
    CreateCheckoutDebitCardPaymentRequest,
    CreatePlanItemRequest,
    CreateCaptureChargeRequest,
    GetSafetyPayTransactionResponse,
    CreateTokenRequest,
    UpdateMetadataRequest,
    CreateCheckoutCardInstallmentOptionRequest,
    UpdatePricingSchemeRequest,
    ListAccessTokensResponse,
    ListUsagesResponse,
    UpdateSubscriptionCardRequest,
    GetSetupResponse,
    GetPlanResponse,
    UpdatePlanRequest,
    CreatePriceBracketRequest,
    GetCardTokenResponse,
    GetCheckoutCardInstallmentOptionsResponse,
    CreateCancelSubscriptionRequest,
    UpdateCardRequest,
    CreatePlanRequest,
    CreateBankTransferPaymentRequest,
    CreatePricingSchemeRequest,
    CreatePhonesRequest,
    CreateVoucherPaymentRequest,
    CreateCheckoutBoletoPaymentRequest,
    UpdateChargeDueDateRequest,
    CreateAccessTokenRequest,
    GetPhoneResponse,
    GetVoucherTransactionResponse,
    ListSubscriptionItemsResponse,
    ListOrderResponse,
    ListAddressesResponse,
    GetDiscountResponse,
    GetCustomerResponse,
    CreateAddressRequest,
    CreateSubscriptionItemRequest,
    CreateOrderRequest,
    GetGatewayResponseResponse,
    CreateDeviceRequest,
    UpdateSubscriptionAffiliationIdRequest,
    GetIncrementResponse,
    CreateThreeDSecureRequest,
    UpdateChargePaymentMethodRequest,
    GetRecipientResponse,
    UpdateRecipientRequest,
    GetGatewayRecipientResponse,
    ListIncrementsResponse,
    CreateAnticipationRequest,
    GetAnticipationLimitsResponse,
    GetInvoiceItemResponse,
    CreateDiscountRequest,
    GetCardResponse,
    CreateBankAccountRequest,
    GetBalanceResponse,
    UpdateOrderItemRequest,
    CreateBoletoPaymentRequest,
    ListAnticipationResponse,
    UpdateAddressRequest,
    GetBoletoTransactionResponse,
    GetLocationResponse,
    GetSubscriptionItemResponse,
    GetDebitCardTransactionResponse,
    CreateTransferSettingsRequest,
    CreateTransferRequest,
    GetGatewayErrorResponse,
    ListTransferResponse,
    CreateUsageRequest,
    CreatePaymentAuthenticationRequest,
    UpdateInvoiceStatusRequest,
    GetUsageResponse,
    CreateSubscriptionRequest,
    CreateApplePayRequest,
    GetAnticipationLimitResponse,
    UpdateCustomerRequest,
    GetSubscriptionResponse,
    GetPeriodResponse,
    CreateDebitCardPaymentRequest,
    CreateApplePayHeaderRequest,
    CreateLocationRequest,
    UpdateOrderStatusRequest,
    CreateCreditCardPaymentRequest,
    ListDiscountsResponse,
    CreateRecipientRequest,
    GetTransferResponse,
    ListRecipientResponse,
    GetDeviceResponse,
    CreatePaymentRequest,
    GetTransactionResponse,
    UpdateRecipientBankAccountRequest,
    UpdateTransferSettingsRequest,
    GetBillingAddressResponse,
    CreateIncrementRequest,
    CreateCashPaymentRequest,
    CreateCancelChargeRequest,
    CreateShippingRequest,
    GetCheckoutCreditCardPaymentResponse,
    CreateChargeRequest,
    CreateTransfer,
    CreateTransactionReportFileRequest,
    CreateCardRequest,
    CreateEmvDataDukptDecryptRequest,
    GetWithdrawTargetResponse,
    CreateCancelChargeSplitRulesRequest,
    UpdateSubscriptionStartAtRequest,
    CreatePixPaymentRequest,
    GetChargesSummaryResponse,
    CreatePrivateLabelPaymentRequest,
    UpdateAutomaticAnticipationSettingsRequest,
    GetSplitResponse,
    ListTransactionsFilesResponse,
    CreateEmvDataTlvDecryptRequest,
    CreateEmvDecryptRequest,
    GetWithdrawSourceResponse,
    CreateConfirmPaymentRequest,
    GetCheckoutDebitCardPaymentResponse,
    GetAnticipationResponse,
    GetPrivateLabelTransactionResponse,
    CreateAutomaticAnticipationSettingsRequest,
    GetCashTransactionResponse,
    UpdateSubscriptionMinimumPriceRequest,
    CreateGooglePayRequest,
    UpdateSubscriptionPaymentMethodRequest,
    CreateAntifraudRequest,
    GetCheckoutBankTransferPaymentResponse,
    GetBankAccountResponse,
    CreateOrderItemRequest,
    CreateSplitOptionsRequest,
    GetTransactionReportFileResponse,
    CreateClearSaleRequest,
    GetUsageReportResponse,
    ListTransfers,
    PixAdditionalInformation,
    GetShippingResponse,
    UpdateCurrentCycleEndDateRequest,
    CreateCheckoutBankTransferRequest,
    CreateCardPaymentContactlessRequest,
    CreateCustomerRequest,
    GetTransferTargetResponse,
    ListWithdrawals,
    GetCheckoutPaymentResponse,
    CreateEmvDataDecryptRequest,
    GetWithdrawResponse,
    GetAutomaticAnticipationResponse,
    CreateCheckoutPaymentRequest,
    CreateCheckoutCreditCardPaymentRequest,
    GetTransfer,
    CreateSplitRequest,
    UpdateCurrentCycleStatusRequest,
    CreateInvoiceRequest,
    GetTransferSettingsResponse,
    CreatePeriodRequest,
    GetPaymentAuthenticationResponse,
    GetThreeDSecureResponse,
    CreateGooglePayHeaderRequest,
    GetOrderItemResponse,
    GetAddressResponse,
    CreateCardPaymentContactlessPOIRequest,
    CreateWithdrawRequest,
    GetSplitOptionsResponse,
    GetCreditCardTransactionResponse,
    ListChargeTransactionsResponse,
    ListCyclesResponse,
    GetInvoiceResponse,
    GetAccessTokenResponse,
    GetTransferSourceResponse,
    CreateSubMerchantRequest,
    GetPixTransactionResponse,
    UpdateSubscriptionDueDaysRequest,
    CreateCheckoutPixPaymentRequest,
    GetCheckoutPixPaymentResponse,
    CreateSubscriptionSplitRequest,
    UpdateSubscriptionSplitRequest,
    GetSubscriptionSplitResponse,
    GetPixPayerResponse,
    GetPixBankAccountResponse,
    ErrorException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
